namespace KBOLauncher.Tests;

using System.Text.Json;
using System.Text.RegularExpressions;
using Xunit;

public sealed class KboRuntimeFlagManifestTests
{
    [Fact]
    public void RuntimeFlagManifest_MatchesGeneratedManagedDefinitions()
    {
        var manifest = ReadManifest();
        var generatedText = File.ReadAllText(RepoPath("src", "KBOLauncher", "Infrastructure", "KboFlags.RuntimeDefinitions.cs"));

        var generatedFlags = Regex.Matches(
                generatedText,
                "new\\(\"(?<key>[^\"]+)\", (?<default>null|true|false), (?<import>true|false), RuntimeFlagLifecycle\\.(?<lifecycle>[A-Za-z]+)\\),")
            .Select(match => new ManifestFlagRow(
                match.Groups["key"].Value,
                match.Groups["default"].Value,
                bool.Parse(match.Groups["import"].Value),
                match.Groups["lifecycle"].Value))
            .ToArray();
        var generatedSingleDivisionFlags = Regex.Matches(
                generatedText,
                "\"(?<key>enable_single_division_allstar_[^\"]+\\.txt)\",")
            .Select(match => match.Groups["key"].Value)
            .ToArray();
        var generatedAliases = Regex.Matches(
                generatedText,
                "new\\(\"(?<legacy>[^\"]+)\", \"(?<canonical>[^\"]+)\"\\),")
            .Select(match => new ManifestAliasRow(match.Groups["legacy"].Value, match.Groups["canonical"].Value))
            .ToArray();

        Assert.Contains("<auto-generated", generatedText);
        Assert.Equal(manifest.Flags, generatedFlags);
        Assert.Equal(manifest.SingleDivisionAllstarFlagKeys.Select(key => key + ".txt").ToArray(), generatedSingleDivisionFlags);
        Assert.Equal(manifest.Aliases, generatedAliases);
    }

    [Fact]
    public void RuntimeFlagManifest_MatchesGeneratedNativeDefinitions()
    {
        var manifest = ReadManifest();
        var uiText = File.ReadAllText(RepoPath("native", "src", "hotkey_window", "views", "mod", "runtime_flags", "runtime_flags.generated.inc"));
        var aliasText = File.ReadAllText(RepoPath("native", "src", "core", "core_flags", "keys", "runtime_flag_aliases.generated.inc"));

        var generatedUiRows = Regex.Matches(
                uiText,
                "\\{ \"(?<key>[^\"]+)\", \"(?<label>[^\"]+)\", (?<enabled>[01]), (?<default>[01]), (?<companion>NULL|\"[^\"]+\"), (?<category>KBO_MOD_FLAG_[A-Z]+) \\},")
            .Select(match => new NativeUiRow(
                match.Groups["key"].Value,
                match.Groups["label"].Value,
                int.Parse(match.Groups["enabled"].Value),
                match.Groups["default"].Value == "1",
                UnquoteNativeNull(match.Groups["companion"].Value),
                match.Groups["category"].Value))
            .ToArray();
        var generatedAliases = Regex.Matches(
                aliasText,
                "strcmp\\(key, \"(?<canonical>[^\"]+)\"\\) == 0\\) \\{\\s+return \"(?<legacy>[^\"]+)\";",
                RegexOptions.Singleline)
            .Select(match => new ManifestAliasRow(match.Groups["legacy"].Value, match.Groups["canonical"].Value))
            .ToArray();

        Assert.Contains("<auto-generated", uiText);
        Assert.Contains("<auto-generated", aliasText);
        Assert.Equal(manifest.NativeUiRows, generatedUiRows);
        Assert.Equal(manifest.Aliases, generatedAliases);
    }

    private static RuntimeFlagManifest ReadManifest()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(RepoPath("config", "kbo-runtime-flags.json")));
        var root = doc.RootElement;
        var flags = root.GetProperty("flags")
            .EnumerateArray()
            .Select(flag => new ManifestFlagRow(
                flag.GetProperty("key").GetString()!,
                JsonBoolOrNull(flag.GetProperty("defaultValue")),
                flag.GetProperty("importLegacy").GetBoolean(),
                flag.GetProperty("lifecycle").GetString()!))
            .ToArray();
        var singleDivisionAllstarFlagKeys = root.GetProperty("singleDivisionAllstarFlagKeys")
            .EnumerateArray()
            .Select(flag => flag.GetString()!)
            .ToArray();
        var aliases = root.GetProperty("aliases")
            .EnumerateArray()
            .Select(alias => new ManifestAliasRow(
                alias.GetProperty("legacyKey").GetString()!,
                alias.GetProperty("canonicalKey").GetString()!))
            .ToArray();
        var uiRows = root.GetProperty("flags")
            .EnumerateArray()
            .Where(flag => flag.TryGetProperty("ui", out _))
            .Select(flag =>
            {
                var ui = flag.GetProperty("ui");
                return new NativeUiRow(
                    flag.GetProperty("key").GetString()!,
                    ui.GetProperty("label").GetString()!,
                    ui.TryGetProperty("enabledValue", out var enabledValue) ? enabledValue.GetInt32() : 1,
                    ui.GetProperty("defaultEnabled").GetBoolean(),
                    ui.TryGetProperty("companionEnableKey", out var companionEnableKey) ? companionEnableKey.GetString() : null,
                    NativeCategoryForLifecycle(flag.GetProperty("lifecycle").GetString()!));
            })
            .ToArray();

        return new RuntimeFlagManifest(flags, singleDivisionAllstarFlagKeys, aliases, uiRows);
    }

    private static string JsonBoolOrNull(JsonElement value)
    {
        return value.ValueKind switch
        {
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            JsonValueKind.Null => "null",
            _ => throw new InvalidDataException($"Expected boolean or null, got {value.ValueKind}."),
        };
    }

    private static string NativeCategoryForLifecycle(string lifecycle)
    {
        return "KBO_MOD_FLAG_" + lifecycle.ToUpperInvariant();
    }

    private static string? UnquoteNativeNull(string value)
    {
        return value == "NULL" ? null : value[1..^1];
    }

    private static string RepoPath(params string[] parts)
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            var candidate = Path.Combine(new[] { dir }.Concat(parts).ToArray());
            if (File.Exists(candidate))
            {
                return candidate;
            }
            dir = Directory.GetParent(dir)?.FullName;
        }

        throw new FileNotFoundException("Could not find repository file.", Path.Combine(parts));
    }

    private sealed record RuntimeFlagManifest(
        ManifestFlagRow[] Flags,
        string[] SingleDivisionAllstarFlagKeys,
        ManifestAliasRow[] Aliases,
        NativeUiRow[] NativeUiRows);

    private sealed record ManifestFlagRow(string Key, string DefaultValue, bool ImportLegacy, string Lifecycle);

    private sealed record ManifestAliasRow(string LegacyKey, string CanonicalKey);

    private sealed record NativeUiRow(
        string Key,
        string Label,
        int EnabledValue,
        bool DefaultEnabled,
        string? CompanionEnableKey,
        string Category);
}
