#ifndef KBOFIX_SRC_MILITARY_SERVICE_MILITARY_TEAM_ADD_GUARD_H_
#define KBOFIX_SRC_MILITARY_SERVICE_MILITARY_TEAM_ADD_GUARD_H_

void kbo_set_team_add_player_guard_trampoline(void* trampoline);
void kbo_clear_team_add_player_guard_trampoline(void);

#endif
