#include "salary_snapshot_state.h"

volatile LONG g_kbo_fa_salary_snapshot_thread_started = 0;
volatile LONG g_kbo_fa_salary_snapshot_phase_event_thread_started = 0;
volatile LONG g_kbo_fa_salary_snapshot_phase_event_write_cursor = 0;
volatile LONG g_kbo_fa_salary_snapshot_phase_event_published_sequence = 0;
volatile LONG g_kbo_fa_salary_snapshot_phase_event_consumed_sequence = 0;
uintptr_t g_kbo_fa_salary_snapshot_phase_event_league_ptrs[KBO_FA_SALARY_PHASE_EVENT_RING_SIZE];
uint32_t g_kbo_fa_salary_snapshot_phase_event_values[KBO_FA_SALARY_PHASE_EVENT_RING_SIZE];
uint32_t g_kbo_fa_salary_snapshot_phase_event_site_rvas[KBO_FA_SALARY_PHASE_EVENT_RING_SIZE];
volatile LONG g_kbo_fa_salary_snapshot_phase_pending_active = 0;
uintptr_t g_kbo_fa_salary_snapshot_phase_pending_league_ptr = 0;
volatile LONG g_kbo_fa_salary_snapshot_phase_pending_value = 0;
volatile LONG g_kbo_fa_salary_snapshot_phase_pending_site_rva = 0;
volatile LONG g_kbo_fa_salary_snapshot_cached_exists_season = 0;
volatile LONG g_kbo_fa_salary_snapshot_cached_exists_value = -1;
