<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>KBOLauncher</AssemblyName>
    <RootNamespace>KBOLauncher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="data\seeds\*.csv" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="data\seeds\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="KBOLauncher.Tests\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>KBOLauncher.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
