#include "runtime_flags.generated.h"

/* <auto-generated />
   Source: config/kbo-runtime-flags.json */
const KboModRuntimeFlagSetting KBO_MOD_RUNTIME_FLAG_SETTINGS[] = {
    { "disable_foreign_injury_replacement", "외국인 부상 대체", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_intl_established_fa_generation_filter", "국제 FA 생성 필터", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_fa_salary_opening_day_snapshot", "FA salary opening-day snapshot", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_no_minor_contract_patch", "No minor-contract patch", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_kbo_ai_fa_status_candidate_insert_hook", "AI FA 후보 훅", 1, 0, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_foreign_ai_offer_candidate_priority_hook", "외국인 AI 제안 우선순위", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_custom_foreign_policy", "커스텀 외국인 정책", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_foreign_signing_branch_patch", "외국인 계약 분기 훅", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_foreign_trade_check_patch", "외국인 트레이드 쿼터 가드", 0, 1, "enable_kbo_foreign_trade_check_patch", KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_sangmu_fa_block_core", "군경팀 FA 차단", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_submit_offer_probe_patch", "Submit-offer probe", 0, 1, "enable_kbo_submit_offer_probe_patch", KBO_MOD_FLAG_RECOVERY },
    { "disable_amateur_assignment_reroute", "아마추어 명성 배정", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_fa_compensation", "FA 보상", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_military_team_add_guard_patch", "군경팀 추가 가드", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_runtime_roster_marker_guard", "런타임 로스터 마커 가드", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "disable_kbo_salary_arbitration_no_withdraw_patch", "Salary arbitration no-withdraw", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_amateur_assignment_verbose_log", "아마추어 배정 상세 로그", 1, 0, NULL, KBO_MOD_FLAG_DIAGNOSTIC },
    { "enable_experimental_runtime_hooks", "런타임 패치 엔진", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_foreign_waiver_ai", "외국인 보류권 AI", 1, 1, NULL, KBO_MOD_FLAG_USER },
    { "enable_foreign_waiver_background_scanner", "외국인 보류권 백그라운드 스캐너", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_foreign_ai_roster_management", "Enhanced foreign AI (Experimental)", 1, 0, NULL, KBO_MOD_FLAG_USER },
    { "enable_foreign_ai_controller", "Foreign AI Controller (Experimental)", 1, 0, NULL, KBO_MOD_FLAG_USER },
    { "enable_kbo_domestic_fa_market_investigation", "국내 FA 시장 조사", 1, 0, NULL, KBO_MOD_FLAG_DIAGNOSTIC },
    { "enable_intl_established_fa_quality_probe_patch", "국제 FA 품질 진단", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_kbo_ai_fa_fallback_patch", "AI FA 폴백 패치", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_kbo_callup_foreign_limit_patch", "Foreign call-up limit patch", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_kbo_offer_eligibility_patch", "계약 제안 가능 여부 패치", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_kbo_player_team_signability_patch", "Player-team signability patch", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_kbo_season_phase_monitor", "시즌 단계 모니터", 0, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_single_division_allstar_events", "Single-division All-Star events", 1, 1, NULL, KBO_MOD_FLAG_USER },
    { "enable_single_division_allstar_runtime_patches", "Single-division All-Star runtime", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_single_division_allstar_settings_patch", "Single-division All-Star settings", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
    { "enable_single_division_allstar_voting_hook", "Single-division All-Star voting", 1, 1, NULL, KBO_MOD_FLAG_RECOVERY },
};

const size_t KBO_MOD_RUNTIME_FLAG_SETTINGS_COUNT =
    sizeof(KBO_MOD_RUNTIME_FLAG_SETTINGS) / sizeof(KBO_MOD_RUNTIME_FLAG_SETTINGS[0]);
