/* <auto-generated />
   Source: config/kbo-runtime-flags.json */
#ifndef KBO_HOTKEY_WINDOW_VIEWS_MOD_RUNTIME_FLAGS_GENERATED_H_
#define KBO_HOTKEY_WINDOW_VIEWS_MOD_RUNTIME_FLAGS_GENERATED_H_

#include <stddef.h>

#include "../info/ui_mod_info_views_internal.h"

extern const KboModRuntimeFlagSetting KBO_MOD_RUNTIME_FLAG_SETTINGS[];
extern const size_t KBO_MOD_RUNTIME_FLAG_SETTINGS_COUNT;

#endif
