// <auto-generated />
// Source: config/ootp-supported-builds.json

internal static class OotpSupportedBuilds
{
    public static readonly OotpSupportedBuild[] All =
    [
        new(0x69F75E6Bu, 0x03919000u, "2026-05-04 Steam"),
    ];
}
