/* <auto-generated />
   Source: config/kbo-runtime-flags.json */
#ifndef KBO_CORE_FLAGS_KEYS_RUNTIME_FLAG_ALIASES_GENERATED_H_
#define KBO_CORE_FLAGS_KEYS_RUNTIME_FLAG_ALIASES_GENERATED_H_

const char* kbo_flag_generated_legacy_json_key_for_key(const char* key);

#endif
