#include "runtime_flag_aliases.generated.h"

#include <string.h>

/* <auto-generated />
   Source: config/kbo-runtime-flags.json */
const char* kbo_flag_generated_legacy_json_key_for_key(const char* key)
{
    if (key == 0) {
        return 0;
    }

    if (strcmp(key, "disable_kbo_no_minor_contract_patch") == 0) {
        return "disable_kbo_no_minor_contract_experimental_patch";
    }

    if (strcmp(key, "enable_foreign_ai_roster_management") == 0) {
        return "enable_foreign_ai_roster_research_hooks";
    }

    return 0;
}
