#ifndef KBOFIX_BOOTSTRAP_OOTP_OFFSETS_PLAYER_H
#define KBOFIX_BOOTSTRAP_OOTP_OFFSETS_PLAYER_H

/* ---- Player offsets ---- */
#define OOTP27_PLAYER_SCAN_BYTES                   0x1800u
#define OOTP27_PLAYER_RETIRED_FLAG_OFFSET          0x40u
#define OOTP27_PLAYER_STATUS_FLAGS_OFFSET          0x41u
#define OOTP27_PLAYER_CURRENT_LEAGUE_ID_OFFSET     0x48u
#define OOTP27_PLAYER_ORIGINAL_LEAGUE_ID_OFFSET    0x4cu
#define OOTP27_PLAYER_LOAN_LEAGUE_ID_OFFSET        0x54u
#define OOTP27_PLAYER_CURRENT_TEAM_ID_OFFSET       0x58u
#define OOTP27_PLAYER_ORIGINAL_TEAM_ID_OFFSET      0x5cu
#define OOTP27_PLAYER_ACTIVE_TEAM_ID_OFFSET        0x60u
#define OOTP27_PLAYER_LOAN_TEAM_ID_OFFSET          0x68u
#define OOTP27_PLAYER_NATION_ID_OFFSET             0x6cu
#define OOTP27_KBO_KOREA_NATION_ID                 177u
#define OOTP27_PLAYER_AGE_OFFSET                   0x7cu
#define OOTP27_PLAYER_ID_OFFSET                    0xb4u
#define OOTP27_PLAYER_GIVEN_NAME_ID_OFFSET         0x20u
#define OOTP27_PLAYER_FAMILY_NAME_ID_OFFSET        0x24u
#define OOTP27_PLAYER_DRAFT_LEAGUE_ID_OFFSET       0xd70u
#define OOTP27_PLAYER_CONTRACT_LEVEL_FLAG_OFFSET   0x8a8u
#define OOTP27_PLAYER_CONTRACT_STATUS_OFFSET       0x8d0u
#define OOTP27_PLAYER_CONTRACT_START_YEAR_OFFSET   0x8d4u
#define OOTP27_PLAYER_CONTRACT_SALARY_Y1_OFFSET    0x8d8u
#define OOTP27_PLAYER_CONTRACT_SALARY_YEARS        10u
#define OOTP27_PLAYER_FA_DEMAND_SALARY_OFFSET      0xd84u
#define OOTP27_PLAYER_DEFAULT_STATUS_PTR_OFFSET     0xe88u
#define OOTP27_PLAYER_DEFAULT_TEAM_ID_OFFSET        0xec4u
#define OOTP27_PLAYER_LOAN_ACTIVE_FLAG_OFFSET      0x842u
#define OOTP27_PLAYER_LOAN_CLEARED_MARKER_OFFSET   0x843u
#define OOTP27_PLAYER_DFA_FLAG_OFFSET              0x85bu
#define OOTP27_PLAYER_LOAN_DIRTY_FLAG_OFFSET       0xf69u
#define OOTP27_PLAYER_RESTRICTED_FLAG_OFFSET       0x83bu
#define OOTP27_PLAYER_SECONDARY_RESTRICTED_FLAG_OFFSET 0x83cu
#define OOTP27_PLAYER_INJURY_ACTIVE_OFFSET         0x874u
#define OOTP27_PLAYER_INJURY_DAYS_LEFT_OFFSET      0x876u
#define OOTP27_PLAYER_MILITARY_EXEMPT_OFFSET       0x895u
#define OOTP27_PLAYER_MILITARY_ACTIVE_OFFSET       0x896u
#define OOTP27_PLAYER_POSITION_GROUP_OFFSET        0xc78u
#define OOTP27_PLAYER_POSITION_ROLE_OFFSET         0xc79u
#define OOTP27_PLAYER_BATTER_CONTACT_CURRENT_OFFSET 0x9f8u
#define OOTP27_PLAYER_BATTER_CONTACT_POTENTIAL_OFFSET 0xa30u
#define OOTP27_PLAYER_BATTER_AVOID_K_CURRENT_OFFSET 0x9fau
#define OOTP27_PLAYER_BATTER_AVOID_K_POTENTIAL_OFFSET 0xa32u
#define OOTP27_PLAYER_BATTER_POWER_CURRENT_OFFSET 0xa00u
#define OOTP27_PLAYER_BATTER_POWER_POTENTIAL_OFFSET 0xa38u
#define OOTP27_PLAYER_BATTER_EYE_CURRENT_OFFSET 0xa02u
#define OOTP27_PLAYER_BATTER_EYE_POTENTIAL_OFFSET 0xa3au
#define OOTP27_PLAYER_PITCHER_STUFF_CURRENT_OFFSET 0xa9au
#define OOTP27_PLAYER_PITCHER_STUFF_POTENTIAL_OFFSET 0xacau
#define OOTP27_PLAYER_PITCHER_MOVEMENT_CURRENT_OFFSET 0xa9cu
#define OOTP27_PLAYER_PITCHER_MOVEMENT_POTENTIAL_OFFSET 0xaccu
#define OOTP27_PLAYER_OVERALL_VALUE_OFFSET         0xcd2u
#define OOTP27_PLAYER_TALENT_VALUE_OFFSET          0xcd4u
#define OOTP27_PLAYER_RATINGS_VALUE_OFFSET         0xcd6u
#define OOTP27_PLAYER_CAREER_VALUE_OFFSET          0xcd8u
#define OOTP27_PLAYER_DRAFT_CLASS_OFFSET           0xdb1u
#define OOTP27_PLAYER_DRAFT_SUBTYPE_OFFSET         0xdb2u
#define OOTP27_PLAYER_DRAFT_ELIGIBLE_OFFSET        0xdb5u
#define OOTP27_PLAYER_DRAFT_EXTRA_FLAG_OFFSET      0xdb6u
#define OOTP27_PLAYER_GENERATION_FLAGS_OFFSET      0xfaau
#define OOTP27_PLAYER_GENERATION_CONTEXT_OFFSET    0xfacu
#define OOTP27_PLAYER_GENERATION_GRADE_OFFSET      0xfadu
#define OOTP27_PLAYER_GENERATION_SPECIAL_OFFSET    0xfb2u


#endif
