#ifndef KBOFIX_BOOTSTRAP_OOTP_OFFSETS_DATES_H
#define KBOFIX_BOOTSTRAP_OOTP_OFFSETS_DATES_H

/* ---- League all-star date fields ---- */
#define OOTP27_SEASON_START_DATE_YEAR_OFFSET  0x118u
#define OOTP27_SEASON_START_DATE_DAY_OFFSET   0x11au
#define OOTP27_SEASON_START_DATE_MONTH_OFFSET 0x11bu
#define OOTP27_SEASON_START_DATE_HOUR_OFFSET  0x11cu
#define OOTP27_SEASON_START_DATE_MIN_OFFSET   0x11du
#define OOTP27_SEASON_START_DATE_SEC_OFFSET   0x11eu
#define OOTP27_ALLSTAR_DATE_YEAR_OFFSET   0x728u
#define OOTP27_ALLSTAR_DATE_DAY_OFFSET    0x72au
#define OOTP27_ALLSTAR_DATE_MONTH_OFFSET  0x72bu
#define OOTP27_ALLSTAR_DATE_HOUR_OFFSET   0x72cu
#define OOTP27_ALLSTAR_DATE_MIN_OFFSET    0x72du
#define OOTP27_ALLSTAR_DATE_SEC_OFFSET    0x72eu

#endif
