#ifndef KBOFIX_SRC_FOREIGN_WAIVER_DECISIONS_INTERNAL_FOREIGN_WAIVER_DECISIONS_STATE_INTERNAL_H_
#define KBOFIX_SRC_FOREIGN_WAIVER_DECISIONS_INTERNAL_FOREIGN_WAIVER_DECISIONS_STATE_INTERNAL_H_

#include "../../../core/sync/lock.h"

extern KboLock g_kbo_foreign_waiver_decision_lock;

#endif
