#ifndef KBOFIX_SRC_PATCH_INSTALLERS_PATCH_INSTALLERS_MILITARY_H_
#define KBOFIX_SRC_PATCH_INSTALLERS_PATCH_INSTALLERS_MILITARY_H_

int install_kbo_military_service_entry_patch(void);
int install_kbo_military_status_update_patch(void);
int install_kbo_military_team_add_guard_patch(void);
int install_kbo_foreign_roster_move_trace_patches(void);
int install_kbo_player_eval_double_trace_patch(void);
int install_kbo_player_eval_cache_trace_patch(void);
int install_kbo_ai_player_quality_trace_patch(void);
int install_kbo_ai_roster_role_check_trace_patch(void);
int install_kbo_ai_roster_post_sort_gate_score_trace_patch(void);
int install_kbo_ai_roster_eligibility_trace_patch(void);
int install_kbo_ai_roster_availability_trace_patch(void);
int install_kbo_ai_roster_f65_update_trace_patch(void);
int install_kbo_ai_team_player_fit_trace_patch(void);
int install_kbo_player_team_status_lookup_trace_patch(void);
int install_kbo_player_default_status_lookup_trace_patch(void);
int install_kbo_pointer_vector_push_trace_patch(void);
int install_kbo_pointer_vector_sort_trace_patch(void);
int install_kbo_ai_roster_priority_compare_patch(void);
int install_kbo_ai_roster_type_compare_patch(void);
int install_kbo_ai_roster_score_compare_patch(void);
int install_kbo_ai_roster_select_trace_patch(void);
int install_kbo_ai_roster_primary_apply_flow_trace_patch(void);
int install_kbo_ai_roster_secondary_main_flow_trace_patch(void);
int install_kbo_ai_roster_secondary_alt_flow_trace_patch(void);
int install_kbo_ai_roster_mark_selected_trace_patch(void);
int install_kbo_ai_roster_selection_reconcile_trace_patch(void);
int install_kbo_ai_roster_apply_selection_trace_patch(void);
int install_kbo_player_team_assignment_trace_patches(void);

#endif
