#ifndef KBOFIX_SRC_PATCH_INSTALLERS_PATCH_INSTALLERS_MILITARY_H_
#define KBOFIX_SRC_PATCH_INSTALLERS_PATCH_INSTALLERS_MILITARY_H_

int install_kbo_military_service_entry_patch(void);
int install_kbo_military_status_update_patch(void);
int install_kbo_military_team_add_guard_patch(void);
int install_kbo_ai_roster_select_trace_patch(void);
int install_kbo_ai_roster_primary_apply_flow_trace_patch(void);
int install_kbo_ai_roster_apply_selection_trace_patch(void);

#endif
