#ifndef KBOFIX_SRC_CUSTOM_EVENTS_CUSTOM_EVENTS_COMMON_H_
#define KBOFIX_SRC_CUSTOM_EVENTS_CUSTOM_EVENTS_COMMON_H_

#include "../../asian_games/state/asian_games_state.h"
#include "../state/custom_event_state.h"
#include "../names/custom_event_names.h"
#include "../lookup/custom_event_lookup.h"
#include "../markers/custom_event_markers.h"
#include "../scan/custom_event_scan.h"
#include "../dispatch/custom_event_dispatch.h"
#include "../monitor/custom_event_monitor.h"
#include "../../schedules/foreign_priority_event_schedule.h"
#include "../../schedules/offseason_transition_schedule.h"
#include "../../asian_games_schedule_seed/state/state_and_paths.h"
#include "../../asian_games_schedule_seed/csv/csv_parse.h"
#include "../../asian_games_schedule_seed/projected/builtin_and_projected.h"
#include "../../asian_games_schedule_seed/import/import_and_load.h"
#include "../../asian_games_schedule_seed/query/query_helpers.h"
#include "../../asian_games/player_eval/asian_games_player_eval.h"
#include "../../asian_games/roster/asian_games_roster_store.h"
#include "../../asian_games_lifecycle/replacement/asian_games_lifecycle_replacement.h"
#include "../../asian_games_lifecycle/departure/asian_games_lifecycle_departure.h"
#include "../../asian_games_lifecycle/final/asian_games_lifecycle_final.h"
#include "../../asian_games/schedule/asian_games_schedule.h"
#include "../../asian_games_selection/pick/selection_pick.h"
#include "../../asian_games_selection/wildcards/wildcards.h"
#include "../../asian_games_selection/missing_org/missing_org.h"
#include "../../asian_games_selection/roster/select_roster.h"
#include "../../asian_games_news/body/body.h"
#include "../../asian_games_news/emit/emit.h"
#include "../../asian_games_news/handlers/handlers.h"
#include "../../asian_games_news/links/links.h"
#include "../../../military_service/players/state/military_player_state.h"
#include "../../../military_service/selection/events/military_selection_event.h"
#include "../../../foreign/common/events/foreign_waiver_events.h"
#include "../../../fa_compensation/due/fa_compensation_due.h"

#endif
